{
 "title": "Disease_predict_service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Используемая оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Гистограмма предсказаний",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "prediction_metric_histogram_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время использования процессора",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статусы запросов к сервису",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Частота запросов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(request_counter_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}